### PR TITLE
[WIP] enable alternate names harvesting by default -- replaced with shared_config changes

### PR DESCRIPTION
**Pull request by peetucket**

### CODE REVIEW

**Comment by darrenleeweber** [comment]
Hesitating to merge this - has it been deployed and tested on the CAP-dev and CAP-stage systems?  What process is involved to make this transition reliable for the prod system?

**Comment by peetucket** [comment]
deployed and did some testing of the harvesting methods that are used by the fortnightly harvest on the command line (ScienceWireHarvester.harvest_pubs_for_authors) on a known author with and without alternate names data and got the expected results

of course, once enabled, the harvesting may include lots of new publications for users with alternate names; possibly increasing the false positives

**Comment by darrenleeweber** [comment]
Could we move the last commit about removing `axlsx` gem into another PR to isolate that from the work here in this PR?  I can't find any code using it, only some possibly related publication code that exports CSV.  I just want to be sure that removing it on the master branch in a separate PR will be clean.  We could then rebase this PR on master once we merge that removal.  OK?

**Comment by darrenleeweber** [comment]
As discussed in slack, the change proposed in this PR might not be a code-repo change.  Rather, it might be a change to the shared_configs repos, e.g.
https://github.com/sul-dlss/shared_configs/tree/sul-pub-cap-dev

If it is only a config change, then we might dispose of this code-repo PR to leave the default behavior on a 'vanilla' repo as it is now.

**Comment by peetucket** [comment]
ok

new PR for unncessary gem removal: https://github.com/sul-dlss/sul_pub/pull/166
shared config PRs for cap-qa, prod and stage (all other environments left alone):
https://github.com/sul-dlss/shared_configs/pull/248
https://github.com/sul-dlss/shared_configs/pull/247
https://github.com/sul-dlss/shared_configs/pull/246

**Comment by darrenleeweber** [comment]
- [x] new PR for unnecessary gem removal: #166
  - merged

shared config PRs:
- [ ] sul-dlss/shared_configs#247 for prod
  - not reviewed or merged
  - pending testing on cap-stage and cap-qa
- [x] sul-dlss/shared_configs#248 for cap-qa
  - merged
  - needs to be deployed and file links updated
  - need to review harvesting logs for any errors etc.
- [x] sul-dlss/shared_configs#246 for cap-stage
  - merged
  - needs to be deployed and file links updated
  - need to review harvesting logs for any errors etc.

**Pull request closed without merging**
