### PR TITLE
Create a critical checks endpoint for okcomputer

### PR DESCRIPTION
**Pull request by mjgiarlo**
## Why was this change made?

This gives us an okcomputer endpoint to hit that includes all checks we might want to alert about, not the ones that trigger partner email. Helps with Nagios integration.

### /status/all screenshot

Screenshot from 2022-04-06 16-36-39

### /status/critical screenshot

Screenshot from 2022-04-06 16-36-57

## How was this change tested?

Tested in cap-dev env.

### CODE REVIEW

**Comment by ndushay** [comment]
could you put in a screen shot of the okcomputer page with and without this?

**Comment by ndushay** [comment]
it kind of feels like we're just reinventing "checks that should alert if they ever aren't passing" and "optional" ... I'm not sure what we gain from this.  Am I missing something?

**Comment by mjgiarlo** [comment]
@ndushay 💬 
> could you put in a screen shot of the okcomputer page with and without this?

Yep! ☝🏻

**Comment by mjgiarlo** [comment]
@ndushay 💬 
> it kind of feels like we're just reinventing "checks that should alert if they ever aren't passing" and "optional" ... I'm not sure what we gain from this. Am I missing something?

Puppet currently configures Nagios to hit `/status/default` instead of `/status/all` for most of our apps, but that gets us a basic up check and nothing else. And we can't just switch over to `/status/all` across the board in prod, because for some apps, `/status/all` contains checks that are not pager-worthy. This is a pattern to create a new `/status/critical` endpoint for these apps in prod so that we get more value out of Nagios checks without burdening Ops.

**Review by ndushay — APPROVED** [review]

**Pull request merged**
