### PR TITLE
Replace rake task to sync cap_profile_ids, removed in #376, connected…

### PR DESCRIPTION
**Pull request by darrenleeweber**
Replacing a rake task removed in #376
- slightly modified to protect prod environment

Connected to #356, #422

### CODE REVIEW

**Comment by atz** [comment]
Alternatively, that can just be done from console or: 
```bash
rails runner -e production 'CapProfileIdRewriter.new.rewrite_cap_profile_ids_from_feed'
```

There really isn't anything to the task.

**Comment by darrenleeweber** [comment]
Yes, it could be run like that too.  With the task, it shows up in `rake -T` (which is where we go when we forget what we want to run).  It tries to protect a production system by excluding running it in `production`.  Of course, there are ways around that and a savy-dev should be able to find a way around it, if necessary.  The production "protection" is just for a user who might make a mistake.

**Comment by atz** [comment]
I thought you described this as being run on stage.  Am I recalling correctly?  If so, that is weird, because stage has `RAILS_ENV=production`.

**Comment by darrenleeweber** [comment]
Allow it to run on a production system, but only after user confirmation.

**Comment by darrenleeweber** [comment]
The team voted to keep the file in #422 and this rake task is useful.

**Pull request merged**
