### PR TITLE
Changes pub_hash validation to support publications submitted by CAP.

### LINKED ISSUE #1331: Error when creating publication via create endpoint
## Backtrace

    line 88 of [PROJECT_ROOT]/app/controllers/publications_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50046/faults/79596536)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1331

## Why was this change made?
CAP submitting an application was resulting in an error due to validation.

## How was this change tested?
NA

## Which documentation and/or configurations were updated?
pub_hash_schema.yml

### CODE REVIEW

**Comment by peetucket** [comment]
I added a commit to update the tests to add the `additionalProperties` and added a new test that better mimics what they are actually sending us.  I tested in localhost and it seems fine to me.  Thoughts?

**Review by peetucket — APPROVED** [review]
I think LGTM for testing in UAT

**Comment by peetucket** [comment]
BTW - the updates to the tests cause them to fail on main and pass here, so that's a good sign.

**Comment by justinlittman** [comment]
Looks good to me.

**Pull request merged**
