### PR TITLE
WOS process records src handler

### PR DESCRIPTION
**Pull request by darrenleeweber**
Work from #712 prompted reconsideration of the fault-tolerance for processing records when the src record fails to save.  The changes here handle failures to save, log a message and move on.  Any src record that fails to save will be skipped in the process.

### CODE REVIEW

**Comment by atz** [comment]
How are you expecting this to fail?  I mean, I understand the *theory*, I just don't see any way for this to get tripped up given there are no significant validations on the model.  

You might wait to try to add this in until I'm done consolidating queries in processing.  I expect to replace the entire series of record writes with a single `create!` statement for all of them.

**Comment by darrenleeweber** [comment]
- just want to be sure that it's not possible to save a publication/contribution without first saving the src data, because the src might never get saved if that happens (i.e. the UIDs are culled if they match a contribution)
- using `create!` with the pub-hash-update attr would be better
  - it could either get modified here in this PR or wait on another PR

**Comment by darrenleeweber** [comment]
I've pushed up changes to be consistent with changes in #716 (to avoid conflicts when one or other is merged).

**Comment by darrenleeweber** [comment]
Superceded by #721 and #727

**Pull request closed without merging**
