### PR TITLE
Gemfile - remove rest-client, replaced by Faraday with http-client

### PR DESCRIPTION
**Pull request by darrenleeweber**
This is prompted by analysis from #417, i.e. the application might not be using rest-client any longer.

On this branch, I've run all the specs without any VCR recordings, i.e.
```
$ rm -rf fixtures/vcr_cassettes/*
$ bundle exec rake

Finished in 3 minutes 5.9 seconds (files took 4.5 seconds to load)
1224 examples, 0 failures, 31 pending
```

`git grep RestClient` returns no matches.  There are many uses of `Faraday`, i.e.

```
$ git grep 'Faraday' app/ lib/
lib/clarivate/links_client.rb:43:      # @return [Faraday::Connection]
lib/clarivate/links_client.rb:45:        @connection ||= Faraday.new(url: host) do |faraday|
lib/clarivate/links_client.rb:46:          faraday.use Faraday::Response::RaiseError
lib/clarivate/links_client.rb:81:      # @param response [Faraday::Response]
lib/pubmed_client.rb:19:    conn = Faraday.new(url: Settings.PUBMED.BASE_URI) do |faraday|
lib/science_wire/request.rb:32:      # @return [Faraday::Connection]
lib/science_wire/request.rb:35:          conn = Faraday.new(url: Settings.SCIENCEWIRE.BASE_URI) do |faraday|
lib/science_wire/request.rb:36:            faraday.use Faraday::Response::RaiseError
lib/science_wire/request.rb:51:      # @return [Faraday::Response]
lib/science_wire_client.rb:24:  rescue Faraday::TimeoutError => te
lib/science_wire_client.rb:25:    NotificationManager.error(te, 'Faraday::TimeoutError during ScienceWire Suggestions API call', self)
lib/science_wire_client.rb:205:  rescue Faraday::TimeoutError => te
lib/science_wire_client.rb:206:    NotificationManager.error(te, 'Faraday::TimeoutError during ScienceWire Publication Query API POST request', self)
lib/science_wire_client.rb:226:  rescue Faraday::TimeoutError => te
lib/science_wire_client.rb:227:    NotificationManager.error(te, 'Faraday::TimeoutError during ScienceWire Publication Query API GET request', self)
lib/science_wire_client.rb:260:  rescue Faraday::TimeoutError => te
lib/science_wire_client.rb:261:    NotificationManager.error(te, 'Faraday::TimeoutError during ScienceWire Publication Items API GET request', self)
lib/tasks/sul.rake:55:    conn = Faraday.new(:url=>args[:server])
```
```
$ git grep 'faraday.adapter' app/ lib/
lib/clarivate/links_client.rb:47:          faraday.adapter :httpclient
lib/pubmed_client.rb:24:      faraday.adapter :httpclient
lib/science_wire/request.rb:41:            faraday.adapter :httpclient
```

### CODE REVIEW

**Comment by atz** [comment]
The dependency part looks good.  I don't understand the VCR updates (deletions?) though.  Were there a bunch of cassettes just not being used?

**Comment by darrenleeweber** [comment]
In the past, whenever we want to be sure API calls are working and whenever we want to update the VCR cassettes, we have removed them all and re-run the specs to recreate them.  To double-check that we do not use rest-client, that's what was done here.

**Comment by darrenleeweber** [comment]
The `git status` on the VCR update was
```
 git status
On branch remove-rest-client
Your branch is up-to-date with 'origin/remove-rest-client'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   fixtures/vcr_cassettes/PubmedHarvester/_search_all_sources_by_pmid/mix_of_local_plus_SW/pubmed_results/does_not_do_any_filtering_with_a_resultset_of_2_manual/batch_pubs.yml
	modified:   fixtures/vcr_cassettes/PubmedHarvester/_search_all_sources_by_pmid/mix_of_local_plus_SW/pubmed_results/filters_out_batch/manual_pubs_from_the_resultset_if_SW/pubmed_records_were_found.yml
	modified:   fixtures/vcr_cassettes/PubmedHarvester/_search_all_sources_by_pmid/searches_ScienceWire_by_pmid_when_not_found_locally_and_returns_a_pubhash.yml
	modified:   fixtures/vcr_cassettes/PubmedHarvester/_search_all_sources_by_pmid/searches_for_a_local_Publication_by_pmid_and_returns_a_pubhash.yml
	modified:   fixtures/vcr_cassettes/PubmedSourceRecord/_get_pubmed_record_from_pubmed/extracts_fields_-_pmid.yml
	modified:   fixtures/vcr_cassettes/PubmedSourceRecord/_get_pubmed_record_from_pubmed/returns_an_instance_of_PubmedSourceRecord.yml
	modified:   fixtures/vcr_cassettes/PubmedSourceRecord/_source_as_hash/DOI_extraction/constructs_a_URL_based_on_the_DOI.yml
	modified:   fixtures/vcr_cassettes/PubmedSourceRecord/_source_as_hash/DOI_extraction/extracts_from_ArticleId/works_when_ELocationID_is_missing.yml
	modified:   fixtures/vcr_cassettes/PubmedSourceRecord/_source_as_hash/DOI_extraction/extracts_from_ArticleId/works_when_ELocationID_is_present.yml
	modified:   fixtures/vcr_cassettes/PubmedSourceRecord/_source_as_hash/DOI_extraction/extracts_from_ArticleId/works_when_record_is_longer_than_64kb.yml
	modified:   fixtures/vcr_cassettes/PubmedSourceRecord/_source_as_hash/DOI_extraction/extracts_from_ELocationID/works_when_ArticleId_is_missing.yml
	modified:   fixtures/vcr_cassettes/ScienceWireClient/_get_full_sciencewire_pubs_for_wos_ids/returns_a_Nokogiri_XML_Document_containing_all_SW_pubs_when_passed_an_array_of_WebOfScience_ids.yml
	modified:   fixtures/vcr_cassettes/ScienceWireClient/_get_pub_by_doi/returns_an_array_with_one_pubhash.yml
	modified:   fixtures/vcr_cassettes/ScienceWireClient/_get_sciencewire_id_suggestions/gets_suggestions_from_journals.yml
	modified:   fixtures/vcr_cassettes/ScienceWireClient/_get_sciencewire_id_suggestions/returns_suggestions_for_email_address_and_name.yml
	modified:   fixtures/vcr_cassettes/ScienceWireClient/_query_sciencewire_by_author_name/with_common_last_name_first_name/returns_a_list_of_sciencewire_ids.yml
	modified:   fixtures/vcr_cassettes/ScienceWireClient/_query_sciencewire_by_author_name/with_uncommon_last_name_first_name_and_max_rows_4/returns_an_empty_array.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_from_directory_of_wos_id_files/processes_only_bibtex_items_of_type_inproceedings.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_pubs_for_author_ids/for_valid_author/calls_write_counts_to_log.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_pubs_for_author_ids/when_existing_pubmed_pub/updates_an_existing_pubmed_publication_with_sciencewire_data.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_pubs_for_author_ids/when_no_existing_publication/adds_new_contributions.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_pubs_for_author_ids/when_no_existing_publication/adds_new_publications.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_pubs_for_author_ids/when_run_consecutively/should_be_idempotent_for_contributions.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_pubs_for_author_ids/when_run_consecutively/should_be_idempotent_for_pubs.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_sw_pubs_by_wos_id_for_author/creates_ScienceWire_Publications_with_an_array_of_WebOfScience_IDs_for_a_given_author.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_sw_pubs_by_wos_id_for_author/does_not_create_duplicate_publication_or_contribution.yml
	modified:   fixtures/vcr_cassettes/ScienceWireHarvester/_harvest_sw_pubs_by_wos_id_for_author/does_not_create_empty_values_in_the_pub_hash_for_pmid_or_an_empty_PMID_identifier.yml
	modified:   fixtures/vcr_cassettes/SciencewireSourceRecord/instance_methods/_sciencewire_update/updates_the_is_active_field.yml
	modified:   fixtures/vcr_cassettes/SciencewireSourceRecord/instance_methods/_sciencewire_update/updates_the_pmid_field.yml
	modified:   fixtures/vcr_cassettes/SciencewireSourceRecord/instance_methods/_sciencewire_update/updates_the_source_data_field.yml
	modified:   fixtures/vcr_cassettes/SciencewireSourceRecord/instance_methods/_sciencewire_update/updates_the_source_fingerprint_field.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/_id/returns_a_pub_with_valid_bibjson_for_sw_harvested_records.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_doi/does_not_query_sciencewire_if_there_is_an_existing_publication_with_the_doi.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_doi/returns_one_document_.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_pmid/returns_one_document.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_title_/does_a_sciencewire_title_search.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_title_/returns_bibjson/with_metadata_section.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_title_/returns_bibjson/with_records_section.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_title_/returns_results_that_match_the_requested_title.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_title_/returns_results_that_match_the_requested_year.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/GET_/publications/sourcelookup_/_title_/with_maxrows_number_of_records.yml
	deleted:    fixtures/vcr_cassettes/SulBib_API/PATCH_/authorship/failure/behaves_like_it_issues_errors_for_cap_profile_id/returns_404_when_it_fails_to_find_a_cap_profile_id.yml
	deleted:    fixtures/vcr_cassettes/SulBib_API/POST_/authorship/failure/behaves_like_it_issues_errors_for_cap_profile_id/returns_404_when_it_fails_to_find_a_cap_profile_id.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/POST_/authorship/success/with_cap_profile_id/behaves_like_it_creates_new_contributions_and_publications/for_a_new_PubMed_publication/adds_new_publication.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/POST_/authorship/success/with_cap_profile_id/behaves_like_it_creates_new_contributions_and_publications/for_a_new_PubMed_publication/adds_proper_identifiers_section.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/POST_/authorship/success/with_cap_profile_id/behaves_like_it_creates_new_contributions_and_publications/for_a_new_ScienceWire_publication/adds_new_ScienceWire_publication.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/POST_/authorship/success/with_cap_profile_id/behaves_like_it_creates_new_contributions_and_publications/for_a_new_ScienceWire_publication/adds_new_ScienceWire_publication_with_proper_identifiers_section.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/POST_/authorship/success/with_sul_author_id/behaves_like_it_creates_new_contributions_and_publications/for_a_new_PubMed_publication/adds_new_publication.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/POST_/authorship/success/with_sul_author_id/behaves_like_it_creates_new_contributions_and_publications/for_a_new_PubMed_publication/adds_proper_identifiers_section.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/POST_/authorship/success/with_sul_author_id/behaves_like_it_creates_new_contributions_and_publications/for_a_new_ScienceWire_publication/adds_new_ScienceWire_publication.yml
	modified:   fixtures/vcr_cassettes/SulBib_API/POST_/authorship/success/with_sul_author_id/behaves_like_it_creates_new_contributions_and_publications/for_a_new_ScienceWire_publication/adds_new_ScienceWire_publication_with_proper_identifiers_section.yml
	modified:   fixtures/vcr_cassettes/doi_search_manual_doi_local.yml
	modified:   fixtures/vcr_cassettes/doi_search_spec_one_doc.yml
	modified:   fixtures/vcr_cassettes/pub_med_client_spec_returns_a_list.yml
	modified:   fixtures/vcr_cassettes/pub_med_client_spec_returns_an_empty_array.yml
```

**Comment by darrenleeweber** [comment]
Using `gitk` to look at some of the VCR changes, most of them are changes in Faraday version or timestamp data, e.g.
```
     headers:
       User-Agent:
-      - Faraday v0.9.2
+      - Faraday v0.13.1
       Accept:
       - "*/*"
       Accept-Encoding:
       - gzip,deflate
       Date:
-      - Thu, 02 Jun 2016 22:09:56 GMT
+      - Mon, 13 Nov 2017 20:58:04 GMT
       Licenseid:
       - Settings.SCIENCEWIRE.LICENSE_ID
       Host:
@@ -66,7 +66,7 @@ http_interactions:
       X-Powered-By:
       - ASP.NET
       Date:
-      - Thu, 02 Jun 2016 22:09:57 GMT
+      - Mon, 13 Nov 2017 20:58:57 GMT
       Content-Length:
       - '278'
```

**Comment by atz** [comment]
Yeah, when I run CI on this branch, with *no internet access*, I get 22 failures, but they are all DNS lookups in `web_of_science` specs:
```
SocketError:
  getaddrinfo: nodename nor servname provided, or not known (search.webofknowledge.com:80)
```
Not HTTP itself. Those *could* be hiding potential errors where HTTP requests would have been made subsequently, but I'm not very worried about it.  Works for me.

**Pull request merged**
