### PR TITLE
Replace squash with honeybadger and simplify exception reporting

### LINKED ISSUE #121: monitoring framework: Switch from squash to honeybadger
see https://github.com/sul-dlss/sul_pub/issues/119

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #121

### CODE REVIEW

**Comment by drh-stanford** [comment]
The coverage report shouldn't be a problem although it marked the PR as failed. 

But I'm confused as to where the Honeybadger configuration comes from (i.e., the API key)? If it's shared configs, shouldn't the deploy scriptie link to it?

**Comment by cbeer** [comment]
@drh-stanford you're right, thanks for catching it. fixed up now.

**Comment by drh-stanford** [comment]
hmmm. i'm not seeing the `honeybadger.yml` in the `sul-pub-prod` branch in shared configs but it is in `sul-pub-cap-qa`.  also, is there a noop `honeybadger.yml` file that we can put for developer laptops in `sul-pub-dev-solo`?

**Comment by cbeer** [comment]
I put the file on this branch: https://github.com/sul-dlss/shared_configs/blob/sulcap-prod/config/honeybadger.yml. I don't see a `sul-pub-prod` branch?

The absence of the file should be sufficiently a no-op for our purposes, no?

**Comment by drh-stanford** [comment]
@tallenaz what are the correct shared config branches for CAP?

**Comment by tallenaz** [comment]
@drh-stanford puppet shows that the shared_configs branches are named `sul-pub-prod`, `sul-pub-cap-dev`, `sul-pub-cap-qa` and `sul-pub-dev`

**Comment by drh-stanford** [comment]
Ok, so we need some PRs that puts the `honeybadger.yml` into each of the shared config branches described ^^^. Because the CAP-QA and CAP-Dev both run in Rails `production` mode, we'll need to set the `env` parameter in `honeybadger.yml` I believe (see http://docs.honeybadger.io/lib/ruby.html).

Also, there are "CAP" and "cap" projects in Honeybadger. It looks like "CAP" is being used but not "cap" -- can we delete that one?

**Pull request merged**
