### PR TITLE
Identifier normalization refactored with specs

### PR DESCRIPTION
**Pull request by darrenleeweber**
Building on #246 and #381 to refactor and add specs, no more tech-debt

@atz requested additional specs

TODO:
- [x] check the required form for ISBN identifiers
  - we are punting on ISBN until a fix for #393 is available, then revert 6f3c024

### CODE REVIEW

**Comment by atz** [comment]
Can you squash some of these 37 commits?

**Comment by darrenleeweber** [comment]
I don't want to squash the atomic refactoring paper trail, following a refactoring process.  It was always green on my laptop (some of the travis failures were rubocop trivia).  When it was red, I usually made a comment as such in the commit.  Each commit represents a progressive movement toward where it is now and previous versions are useful for tracking changes.  It costs nothing to leave them as a record of the transformation.

**Comment by atz** [comment]
The whole point of Metz's "lean on green" strategy was to allow you to make successive changes with confidence.  That does not extend to committing for every change.  Commits are logical units, not a record of your development process, so 38 commits is **noise**.  If they truly are atomic and distinct, then why they are in the same PR is unclear.

IMO, you can at least squash all the failed CI builds into the next passing commit, since those states do not represent ones that we would ever want to revert to.  

Honestly, you objected when I had seven commits in one PR because that was too much to review, demanding even single-line commits be broken out to separate PRs.  So I'm pretty sure you would never accept this PR if you hadn't authored it.

**Comment by darrenleeweber** [comment]
It's too much work to squash these commits.  I did squash some along the way.  Squashing some of these will require shuffling commits and resolving conflicts and it's just not worth the time.  If this were all done in the original PR that was not already on master, it could be a different story and maybe worth the time.  I've already taken weeks to meet all your requirements.  I'm done with this.

**Comment by darrenleeweber** [comment]
I've split out #400 to focus on the extract/move methods that landed in the `PublicationIdentifier` and the use of the `PublicationIdentifier#identifier` in the Publication.  We need to first review/merge #400 and then rebase this PR to evaluate the commit history and resolve conflicts.

**Comment by darrenleeweber** [comment]
Rebased on master after #400 merged.

**Comment by darrenleeweber** [comment]
I've split out #406 to focus on changes in the identifier parsers.  We need to first review/merge #406 and then rebase this PR to evaluate the commit history and resolve conflicts.

**Comment by darrenleeweber** [comment]
Rebased on master after #406 merged.

**Comment by darrenleeweber** [comment]
@atz - done with extracting separate PRs and squashing commits.

**Pull request merged**
